query transactions(
  $owners: [String!]
  $recipients: [String!]
  $tags: [TagFilter!]
  $block: BlockFilter
  $first: Int
  $after: String
) {
  transactions(
    owners: $owners
    recipients: $recipients
    tags: $tags
    block: $block
    first: $first
    after: $after
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        anchor
        signature
        owner {
          address
          key
        }
        recipient
        tags {
          name
          value
        }
        block {
          id
          height
          timestamp
          previous
        }
        fee {
          winston
          ar
        }
        quantity {
          winston
          ar
        }
        data {
          size
          type
        }
      }
    }
  }
}

query transaction($id: ID!) {
  transaction(id: $id) {
    id
    anchor
    signature
    owner {
      address
      key
    }
    recipient
    tags {
      name
      value
    }
    block {
      id
      height
      timestamp
      previous
    }
    fee {
      winston
      ar
    }
    quantity {
      winston
      ar
    }
    data {
      size
      type
    }
  }
}
